export const selectedLinks:{id:string | number; image:string; label:string; background?:string}[] = [
  {id:1, label:'GitHub', image:'/images/icon-github.svg', background:'#1A1A1A'},
  {id:2, label:'Frontend Mentor', image:'/images/icon-frontend-mentor.svg', background:'#FFF'},
  {id:3, label:'Twitter', image:'/images/icon-twitter.svg', background:'#43B7E9'},
  {id:4, label:'LinkedIn', image:'/images/icon-linkedin.svg', background:'#2D68FF'},
  {id:5, label:'YouTube', image:'/images/icon-youtube.svg', background:'#EE3939'},
  {id:6, label:'Facebook', image:'/images/icon-facebook.svg', background:'#2442AC'},
  {id:7, label:'Twitch', image:'/images/icon-twitch.svg', background:'#EE3FC8'},
  {id:8, label:'Dev.to', image:'/images/icon-devto.svg', background:'#333333'},
  {id:9, label:'Codewars', image:'/images/icon-codewars.svg', background:'#8A1A50'},
  {id:10, label:'Codepen', image:'/images/icon-codepen.svg', background:'#000000'},
  {id:11, label:'freeCodeCamp', image:'/images/icon-freecodecamp.svg', background:'#302267'},
  {id:12, label:'GitLab', image:'/images/icon-gitlab.svg', background:'#EB4925'},
  {id:13, label:'Hashnode', image:'/images/icon-hashnode.svg', background:'#0330D1'},
  {id:14, label:'Stack Overflow', image:'/images/icon-stack-overflow.svg', background:'#EC7100'},
]