export const selectedLinks:{id:string | number; image:string; label:string;}[] = [
  {id:1, label:'GitHub', image:'/images/icon-github.svg'},
  {id:2, label:'Frontend Mentor', image:'/images/icon-frontend-mentor.svg'},
  {id:3, label:'Twitter', image:'/images/icon-twitter.svg'},
  {id:4, label:'LinkedIn', image:'/images/icon-linkedin.svg'},
  {id:5, label:'YouTube', image:'/images/icon-youtube.svg'},
  {id:6, label:'Facebook', image:'/images/icon-facebook.svg'},
  {id:7, label:'Twitch', image:'/images/icon-twitch.svg'},
  {id:8, label:'Dev.to', image:'/images/icon-devto.svg'},
  {id:9, label:'Codewars', image:'/images/icon-codewars.svg'},
  {id:10, label:'Codepen', image:'/images/icon-codepen.svg'},
  {id:11, label:'freeCodeCamp', image:'/images/icon-freecodecamp.svg'},
  {id:12, label:'GitLab', image:'/images/icon-gitlab.svg'},
  {id:13, label:'Hashnode', image:'/images/icon-hashnode.svg'},
  {id:14, label:'Stack Overflow', image:'/images/icon-stack-overflow.svg'},
]