import './globals.css'
import { Inter, Instrument_Sans } from 'next/font/google'

const InstrumentSans = Instrument_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={InstrumentSans.className}>{children}</body>
    </html>
  )
}
